name: Commit File

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'
      - 'poetry.lock'
      - 'pyproject.toml'
  push:
    branches: ["main"]
    paths:
      - '**.py'
      - 'poetry.lock'
      - 'pyproject.toml'

env:
  UPDATE_FILE: test.txt

jobs:
  update-file:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
        if: github.event_name == 'pull_request'

      - name: Checkout
        uses: actions/checkout@v4
        if: github.event_name != 'pull_request'

      - name: Create File
        run: |
          date +%s > ${{ env.UPDATE_FILE }}

      - uses: EndBug/add-and-commit@v9 
        with:
          add: '${{ env.UPDATE_FILE }}'
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          committer_name: GitHub
          committer_email: noreply@github.com
          message: Commit from GitHub Actions to update ${{ env.UPDATE_FILE }} file
          push: true
