name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    environment: dev

    env:
      WORKING_DIR: outyet
      DOCKERHUB_REPO_NAME: outyet
      DOCKERHUB_IMAGE_APP_VERSION: 1.0.0
    
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
      
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{ defaultContext }}:${{ env.WORKING_DIR }}"
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO_NAME }}:latest,
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO_NAME }}:${{ env.DOCKERHUB_IMAGE_APP_VERSION }}
