---
on:
  # schedule:
  #   # at 00:00 on day-of-month 1
  #   - cron: '0 0 1 * *'
  workflow_dispatch:

name: Push Tag

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: v
          dry_run: true
